// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCOSWXMAA6sB3PsuqCbcf6Eb6X1gWbTbg',
    appId: '1:708447009891:web:48feab83ee1c136fa20c56',
    messagingSenderId: '708447009891',
    projectId: 'literalivre',
    authDomain: 'literalivre.firebaseapp.com',
    databaseURL: 'https://literalivre.firebaseio.com',
    storageBucket: 'literalivre.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuyLuRp4JEsc2kQWs_tf1_L4HJTX5xwuY',
    appId: '1:708447009891:android:479858458d0528c2a20c56',
    messagingSenderId: '708447009891',
    projectId: 'literalivre',
    databaseURL: 'https://literalivre.firebaseio.com',
    storageBucket: 'literalivre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbOP6UsU6kff_8OTrQ5dmYbWl1DAaYLk0',
    appId: '1:708447009891:ios:7e18d4f643b20194a20c56',
    messagingSenderId: '708447009891',
    projectId: 'literalivre',
    databaseURL: 'https://literalivre.firebaseio.com',
    storageBucket: 'literalivre.appspot.com',
    iosBundleId: 'com.samuel.discordCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbOP6UsU6kff_8OTrQ5dmYbWl1DAaYLk0',
    appId: '1:708447009891:ios:f04ce12f3ebf5b92a20c56',
    messagingSenderId: '708447009891',
    projectId: 'literalivre',
    databaseURL: 'https://literalivre.firebaseio.com',
    storageBucket: 'literalivre.appspot.com',
    iosBundleId: 'com.example.discordCloneApp.RunnerTests',
  );
}
